/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TrackRouteImport } from './routes/track'
import { Route as ShopRouteImport } from './routes/shop'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as PresentationRouteImport } from './routes/presentation'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ExploreRouteImport } from './routes/explore'
import { Route as EditorialRouteImport } from './routes/editorial'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as VerifyEmailTokenRouteImport } from './routes/verify-email.$token'
import { Route as UserWishlistRouteImport } from './routes/user/wishlist'
import { Route as UserProfileRouteImport } from './routes/user/profile'
import { Route as UserCheckoutRouteImport } from './routes/user/checkout'
import { Route as UserCartRouteImport } from './routes/user/cart'
import { Route as TrackIdRouteImport } from './routes/track.$id'
import { Route as SellerDashboardRouteImport } from './routes/seller/dashboard'
import { Route as ProductIdRouteImport } from './routes/product.$id'
import { Route as AdminDashboardRouteImport } from './routes/admin/dashboard'
import { Route as AuthenticatedWishlistRouteImport } from './routes/_authenticated/wishlist'
import { Route as AuthenticatedNotificationsRouteImport } from './routes/_authenticated/notifications'

const TrackRoute = TrackRouteImport.update({
  id: '/track',
  path: '/track',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopRoute = ShopRouteImport.update({
  id: '/shop',
  path: '/shop',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const PresentationRoute = PresentationRouteImport.update({
  id: '/presentation',
  path: '/presentation',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ExploreRoute = ExploreRouteImport.update({
  id: '/explore',
  path: '/explore',
  getParentRoute: () => rootRouteImport,
} as any)
const EditorialRoute = EditorialRouteImport.update({
  id: '/editorial',
  path: '/editorial',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const VerifyEmailTokenRoute = VerifyEmailTokenRouteImport.update({
  id: '/verify-email/$token',
  path: '/verify-email/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const UserWishlistRoute = UserWishlistRouteImport.update({
  id: '/user/wishlist',
  path: '/user/wishlist',
  getParentRoute: () => rootRouteImport,
} as any)
const UserProfileRoute = UserProfileRouteImport.update({
  id: '/user/profile',
  path: '/user/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const UserCheckoutRoute = UserCheckoutRouteImport.update({
  id: '/user/checkout',
  path: '/user/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const UserCartRoute = UserCartRouteImport.update({
  id: '/user/cart',
  path: '/user/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const TrackIdRoute = TrackIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => TrackRoute,
} as any)
const SellerDashboardRoute = SellerDashboardRouteImport.update({
  id: '/seller/dashboard',
  path: '/seller/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductIdRoute = ProductIdRouteImport.update({
  id: '/product/$id',
  path: '/product/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/admin/dashboard',
  path: '/admin/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedWishlistRoute = AuthenticatedWishlistRouteImport.update({
  id: '/_authenticated/wishlist',
  path: '/wishlist',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedNotificationsRoute =
  AuthenticatedNotificationsRouteImport.update({
    id: '/_authenticated/notifications',
    path: '/notifications',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/editorial': typeof EditorialRoute
  '/explore': typeof ExploreRoute
  '/login': typeof LoginRoute
  '/presentation': typeof PresentationRoute
  '/register': typeof RegisterRoute
  '/shop': typeof ShopRoute
  '/track': typeof TrackRouteWithChildren
  '/notifications': typeof AuthenticatedNotificationsRoute
  '/wishlist': typeof AuthenticatedWishlistRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/product/$id': typeof ProductIdRoute
  '/seller/dashboard': typeof SellerDashboardRoute
  '/track/$id': typeof TrackIdRoute
  '/user/cart': typeof UserCartRoute
  '/user/checkout': typeof UserCheckoutRoute
  '/user/profile': typeof UserProfileRoute
  '/user/wishlist': typeof UserWishlistRoute
  '/verify-email/$token': typeof VerifyEmailTokenRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/editorial': typeof EditorialRoute
  '/explore': typeof ExploreRoute
  '/login': typeof LoginRoute
  '/presentation': typeof PresentationRoute
  '/register': typeof RegisterRoute
  '/shop': typeof ShopRoute
  '/track': typeof TrackRouteWithChildren
  '/notifications': typeof AuthenticatedNotificationsRoute
  '/wishlist': typeof AuthenticatedWishlistRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/product/$id': typeof ProductIdRoute
  '/seller/dashboard': typeof SellerDashboardRoute
  '/track/$id': typeof TrackIdRoute
  '/user/cart': typeof UserCartRoute
  '/user/checkout': typeof UserCheckoutRoute
  '/user/profile': typeof UserProfileRoute
  '/user/wishlist': typeof UserWishlistRoute
  '/verify-email/$token': typeof VerifyEmailTokenRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/editorial': typeof EditorialRoute
  '/explore': typeof ExploreRoute
  '/login': typeof LoginRoute
  '/presentation': typeof PresentationRoute
  '/register': typeof RegisterRoute
  '/shop': typeof ShopRoute
  '/track': typeof TrackRouteWithChildren
  '/_authenticated/notifications': typeof AuthenticatedNotificationsRoute
  '/_authenticated/wishlist': typeof AuthenticatedWishlistRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/product/$id': typeof ProductIdRoute
  '/seller/dashboard': typeof SellerDashboardRoute
  '/track/$id': typeof TrackIdRoute
  '/user/cart': typeof UserCartRoute
  '/user/checkout': typeof UserCheckoutRoute
  '/user/profile': typeof UserProfileRoute
  '/user/wishlist': typeof UserWishlistRoute
  '/verify-email/$token': typeof VerifyEmailTokenRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/contact'
    | '/editorial'
    | '/explore'
    | '/login'
    | '/presentation'
    | '/register'
    | '/shop'
    | '/track'
    | '/notifications'
    | '/wishlist'
    | '/admin/dashboard'
    | '/product/$id'
    | '/seller/dashboard'
    | '/track/$id'
    | '/user/cart'
    | '/user/checkout'
    | '/user/profile'
    | '/user/wishlist'
    | '/verify-email/$token'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/editorial'
    | '/explore'
    | '/login'
    | '/presentation'
    | '/register'
    | '/shop'
    | '/track'
    | '/notifications'
    | '/wishlist'
    | '/admin/dashboard'
    | '/product/$id'
    | '/seller/dashboard'
    | '/track/$id'
    | '/user/cart'
    | '/user/checkout'
    | '/user/profile'
    | '/user/wishlist'
    | '/verify-email/$token'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/contact'
    | '/editorial'
    | '/explore'
    | '/login'
    | '/presentation'
    | '/register'
    | '/shop'
    | '/track'
    | '/_authenticated/notifications'
    | '/_authenticated/wishlist'
    | '/admin/dashboard'
    | '/product/$id'
    | '/seller/dashboard'
    | '/track/$id'
    | '/user/cart'
    | '/user/checkout'
    | '/user/profile'
    | '/user/wishlist'
    | '/verify-email/$token'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ContactRoute: typeof ContactRoute
  EditorialRoute: typeof EditorialRoute
  ExploreRoute: typeof ExploreRoute
  LoginRoute: typeof LoginRoute
  PresentationRoute: typeof PresentationRoute
  RegisterRoute: typeof RegisterRoute
  ShopRoute: typeof ShopRoute
  TrackRoute: typeof TrackRouteWithChildren
  AuthenticatedNotificationsRoute: typeof AuthenticatedNotificationsRoute
  AuthenticatedWishlistRoute: typeof AuthenticatedWishlistRoute
  AdminDashboardRoute: typeof AdminDashboardRoute
  ProductIdRoute: typeof ProductIdRoute
  SellerDashboardRoute: typeof SellerDashboardRoute
  UserCartRoute: typeof UserCartRoute
  UserCheckoutRoute: typeof UserCheckoutRoute
  UserProfileRoute: typeof UserProfileRoute
  UserWishlistRoute: typeof UserWishlistRoute
  VerifyEmailTokenRoute: typeof VerifyEmailTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/track': {
      id: '/track'
      path: '/track'
      fullPath: '/track'
      preLoaderRoute: typeof TrackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop': {
      id: '/shop'
      path: '/shop'
      fullPath: '/shop'
      preLoaderRoute: typeof ShopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/presentation': {
      id: '/presentation'
      path: '/presentation'
      fullPath: '/presentation'
      preLoaderRoute: typeof PresentationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explore': {
      id: '/explore'
      path: '/explore'
      fullPath: '/explore'
      preLoaderRoute: typeof ExploreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/editorial': {
      id: '/editorial'
      path: '/editorial'
      fullPath: '/editorial'
      preLoaderRoute: typeof EditorialRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verify-email/$token': {
      id: '/verify-email/$token'
      path: '/verify-email/$token'
      fullPath: '/verify-email/$token'
      preLoaderRoute: typeof VerifyEmailTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/user/wishlist': {
      id: '/user/wishlist'
      path: '/user/wishlist'
      fullPath: '/user/wishlist'
      preLoaderRoute: typeof UserWishlistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/user/profile': {
      id: '/user/profile'
      path: '/user/profile'
      fullPath: '/user/profile'
      preLoaderRoute: typeof UserProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/user/checkout': {
      id: '/user/checkout'
      path: '/user/checkout'
      fullPath: '/user/checkout'
      preLoaderRoute: typeof UserCheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/user/cart': {
      id: '/user/cart'
      path: '/user/cart'
      fullPath: '/user/cart'
      preLoaderRoute: typeof UserCartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/track/$id': {
      id: '/track/$id'
      path: '/$id'
      fullPath: '/track/$id'
      preLoaderRoute: typeof TrackIdRouteImport
      parentRoute: typeof TrackRoute
    }
    '/seller/dashboard': {
      id: '/seller/dashboard'
      path: '/seller/dashboard'
      fullPath: '/seller/dashboard'
      preLoaderRoute: typeof SellerDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/product/$id': {
      id: '/product/$id'
      path: '/product/$id'
      fullPath: '/product/$id'
      preLoaderRoute: typeof ProductIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/dashboard': {
      id: '/admin/dashboard'
      path: '/admin/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/wishlist': {
      id: '/_authenticated/wishlist'
      path: '/wishlist'
      fullPath: '/wishlist'
      preLoaderRoute: typeof AuthenticatedWishlistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/notifications': {
      id: '/_authenticated/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof AuthenticatedNotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface TrackRouteChildren {
  TrackIdRoute: typeof TrackIdRoute
}

const TrackRouteChildren: TrackRouteChildren = {
  TrackIdRoute: TrackIdRoute,
}

const TrackRouteWithChildren = TrackRoute._addFileChildren(TrackRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ContactRoute: ContactRoute,
  EditorialRoute: EditorialRoute,
  ExploreRoute: ExploreRoute,
  LoginRoute: LoginRoute,
  PresentationRoute: PresentationRoute,
  RegisterRoute: RegisterRoute,
  ShopRoute: ShopRoute,
  TrackRoute: TrackRouteWithChildren,
  AuthenticatedNotificationsRoute: AuthenticatedNotificationsRoute,
  AuthenticatedWishlistRoute: AuthenticatedWishlistRoute,
  AdminDashboardRoute: AdminDashboardRoute,
  ProductIdRoute: ProductIdRoute,
  SellerDashboardRoute: SellerDashboardRoute,
  UserCartRoute: UserCartRoute,
  UserCheckoutRoute: UserCheckoutRoute,
  UserProfileRoute: UserProfileRoute,
  UserWishlistRoute: UserWishlistRoute,
  VerifyEmailTokenRoute: VerifyEmailTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
